---
- name: Тестирование окружения и доступа AWX
  hosts: all
  gather_facts: yes
  become: no

  tasks:
    - name: ТЕСТ 1 | Проверка связи (Ping)
      ansible.builtin.ping:

    - name: ТЕСТ 2 | Сбор информации о целевой ОС
      ansible.builtin.debug:
        msg:
          - "Тип ОС: {{ ansible_distribution }}"
          - "Версия ОС: {{ ansible_distribution_version }}"
          - "Ядро: {{ ansible_kernel }}"

    - name: ТЕСТ 3 | Проверка выполнения команд локально (на Pod'е контейнера AWX-EE)
      delegate_to: localhost
      ansible.builtin.command:
        cmd: whoami
      register: local_user
      changed_when: false

    - name: ТЕСТ 4 | Вывод имени пользователя контейнера
      ansible.builtin.debug:
        var: local_user.stdout
